name: Phoenix Test Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule: # Set the cron for MidNight IST ---UTC
   - cron: "30 18 * * *"
  workflow_dispatch:
    inputs:
      env:
       description: "Environment"
       type: choice
       options: [qa,uat,dev]
       default: qa
       required: true

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Execute Tests
      - name: Execute Test Automation Framework
        run: mvn clean test -DsuiteXmlFile=testng.xml -Denv="${{ github.event.inputs.env }}"

      # Upload Surefire Report
      - name: Upload Surefire Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: SureFire Report
          path: target/surefire-reports/
          retention-days: 10
